name: build-producton

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Backend API
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kayotimoteo/scrum-poker/scrum-poker
          registry: docker.pkg.github.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: apps/api
          dockerfile: Dockerfile.staging
          tags: latest
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/kayotimoteo/scrum-poker:latest
            docker stop api-scrum-poker
            docker rm api-scrum-poker
            docker run -dit --name api-scrum-poker -p 40000:3333 -e ENV=production -e PORT=3333 --network nginx_default docker.pkg.github.com/kayotimoteo/scrum-poker:latest
