name: build-staging-2023

on:
  push:
    branches:
      - staging

jobs:
  backend:
    name: Backend API
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kayotimoteo/scrum-poker/scrum-poker
          registry: docker.pkg.github.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: apps/api
          dockerfile: Dockerfile.staging
          tags: staging
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@v0.1.10
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/kayotimoteo/scrum-poker:staging
            docker stop api-scrum-poker-staging
            docker rm api-scrum-poker-staging
            docker run -dit --name api-scrum-poker-staging -p 40001:3333 -e ENV=staging -e PORT=3333 --network nginx_default docker.pkg.github.com/kayotimoteo/scrum-poker:staging
